author1 = Author.create!(name: "J.R.R. Tolkien")
author2 = Author.create!(name: "George R. R. Martin")
author3 = Author.create!(name: "J.K. Rowling")
author4 = Author.create!(name: "Stephen King")
author5 = Author.create!(name: "Dan Brown")
author6 = Author.create!(name: "H.G. Wells")
author7 = Author.create!(name: "J.D. Salinger")

Book.create!(title: "Lord of the Rings", published: 1954, pages: 1216, author: author1)
Book.create!(title: "A Game of Thrones", published: 1996, pages: 694, author: author2)
Book.create!(title: "Harry Potter and the Philosopher's Stone", published: 1997, pages: 223, author: author3)
Book.create!(title: "The Shining", published: 1977, pages: 447, author: author4)
Book.create!(title: "The Da Vinci Code", published: 2003, pages: 489, author: author5)
Book.create!(title: "The Hobbit", published: 1937, pages: 310, author: author6)
Book.create!(title: "The Catcher in the Rye", published: 1951, pages: 277, author: author7)
